# Travis CI build file for Ghostwriter
#
# Copyright (C) 2017 Arthur M

language: python
python:
        - "2.7"
        - "3.6"
env:
        - GHOSTWRITER_CONFIG=ghostwriter.cfg
install: "pip install -e ."
script: python -m ghostwriter.test

